kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  x509:
    clientCAFile: "{{ .clientCAFile }}"
cgroupDriver: systemd
cgroupsPerQOS: true
clusterDNS:
  - "{{ .clusterDNSIP }}"
clusterDomain: cluster.local
containerLogMaxSize: 50Mi
containerRuntimeEndpoint: unix:///var/run/crio/crio.sock
enforceNodeAllocatable: []
failSwapOn: false
featureGates:
  APIPriorityAndFairness: true
  DisableKubeletCloudCredentialProviders: false
  DownwardAPIHugePages: true
  KMSv1: true
  NetworkLiveMigration: true
  PodSecurity: true
  RotateKubeletServerCertificate: false # TODO
  VSphereControlPlaneMachineSet: true
kubeAPIBurst: 100
kubeAPIQPS: 50
maxPods: 250
nodeStatusReportFrequency: 5m
rotateCertificates: false # TODO
serializeImagePulls: false
serverTLSBootstrap: false # TODO
tlsCertFile: "{{ .tlsCertFile }}"
tlsPrivateKeyFile: "{{ .tlsPrivateKeyFile }}"
tlsMinVersion: VersionTLS12
tlsCipherSuites:
  - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
  - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
  - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
  - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
volumePluginDir: "{{ .volumePluginDir }}"
{{- if .resolvConf }}
resolvConf: "{{ .resolvConf }}"
{{- end }}
