
images:
  - name: quay.io/operator-framework/olm
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:ca8c2a6ce5468a61722f3c6a10cd9bb7ca106fa2042b02abb25ce775651b03d9
  - name: quay.io/operator-framework/configmap-operator-registry
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:4f1fcc3b0e18ac28ac97158af94791b40720c33ad805a303ccbc11bec8953e8b
  - name: quay.io/openshift/origin-kube-rbac-proxy
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:27dbdbf515b938abb4e1a6f6787d52205db72c6eb0ec7e200cb11a91ad6ab9d0

patches:
  - patch: |-
     - op: add
       path: /spec/template/spec/containers/0/env/-
       value:
         name: OPERATOR_REGISTRY_IMAGE 
         value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:4f1fcc3b0e18ac28ac97158af94791b40720c33ad805a303ccbc11bec8953e8b
     - op: add
       path: /spec/template/spec/containers/0/env/-
       value:
         name: OLM_IMAGE 
         value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:ca8c2a6ce5468a61722f3c6a10cd9bb7ca106fa2042b02abb25ce775651b03d9
    target:
      kind: Deployment
      labelSelector: app=catalog-operator
