
images:
  - name: multus-cni
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:078ee97092f81deeaf759bfd9c6521dec044aa1890690e050c5b7fec7e5d2322
  - name: container-networking-plugins
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:6ec2eaaddc4586dbec769d3f62f593b47f009de248454d80293e5e5f82d02106
