
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:3ff01451bfe36832041ca6151051226fbe3fcdab1291f8fe74fa3f3c6913b31f
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:d0e4717ab59e84f15892fae3084b120a91beeb82974b4ff559ee347fdfc78139
